version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    volumes:
      - ./RutasMoteras/:/code
    # Cambiar base de datos a PostgresSQL
    # depends_on:
    #   - db
      
  # Base de datos postgres
  # db:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  # postgres_data:
