# Generated by Django 3.2 on 2023-05-16 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comunidadesAutonomas', '0001_initial'),
        ('motos', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=256)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comunidadesAutonomas.comunidades')),
                ('tipomoto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='motos.motos')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
