# Generated by Django 3.2 on 2023-05-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('rutas', '0002_auto_20230516_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.myuser'),
        ),
    ]
