# Generated by Django 3.2 on 2023-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_alter_ruta_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.CharField(max_length=1024),
        ),
    ]
