# Generated by Django 3.2 on 2023-05-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=256, unique=True)),
                ('habitad', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Motos',
                'verbose_name_plural': 'Motos',
            },
        ),
    ]
